# .github/workflows/update-odds.yml (Using Chrome/Chromedriver)

name: Update Tennis Odds Page

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs every day at 06:00 UTC
    - cron: '0 6 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # --- Install Chromium and Chromedriver ---
      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update -y
          # Install chromium-browser and the matching chromedriver via apt
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # --- Verify Versions (Optional but Recommended) ---
      - name: Verify Chromium Version
        run: chromium-browser --version

      - name: Verify Chromedriver Version
        run: chromedriver --version

      # --- Install Python Dependencies ---
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # --- Run Scraper (No xvfb needed for Chrome headless) ---
      - name: Run Scraper to Generate Dated CSV
        # Note: Removed xvfb-run prefix
        run: python save_sackmann_data.py

      # --- Steps to Commit the generated CSV back to the repository ---
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage New CSV File(s)
        run: |
          if [ -d "data_archive" ]; then
            git add data_archive/*.csv
            echo "Staged CSV files from data_archive."
          else
            echo "data_archive directory not found, nothing to stage."
          fi

      - name: Commit New CSV(s) if any were staged
        run: |
          if ! git diff --staged --quiet; then
            git commit -m "Add/Update Sackmann data CSV(s) (`date -u +%Y-%m-%d`)"
            echo "Committed CSV changes."
          else
            echo "No changes to CSV files to commit."
          fi

      - name: Push CSV Changes
        run: |
           if [ $(git rev-list --count origin/${{ github.ref_name }}..${{ github.ref_name }}) -gt 0 ]; then
             git push origin ${{ github.ref_name }}
             echo "Pushed CSV commits to origin."
           else
             echo "No new commits to push."
           fi

      # --- End of CSV Commit Steps ---

      - name: Generate HTML Page from Latest CSV
        run: python generate_page.py

      - name: Verify HTML Output
        run: |
          if [ ! -f index.html ]; then
            echo "Error: index.html not found after generation step."
            exit 1
          fi
          if ! grep -q "Last updated:" index.html; then
            echo "Warning: index.html does not seem to contain the 'Last updated' timestamp."
            # exit 1
          fi
          if grep -q "" index.html; then
            echo "Warning: index.html might still contain the table placeholder."
            # exit 1
          fi
          echo "HTML verification check complete."

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Upload the current directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
