# .github/workflows/main.yml (Add CSV Check)

name: Update Tennis Odds Page

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Chromium and Chromedriver
        run: |
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Verify Chromium Version
        run: chromium-browser --version

      - name: Verify Chromedriver Version
        run: chromedriver --version

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper to Generate Dated CSV
        run: python save_sackmann_data.py # Removed xvfb-run as it's not needed for Chrome

      # *** NEW STEP: Verify CSV was created ***
      - name: Verify CSV Creation
        run: |
          # Find files matching the pattern. Use 'find' for better handling of filenames.
          # Use 'head -n 1' to get just one filename if multiple match (e.g., if run twice quickly)
          # Use 'wc -l' to count how many files were found.
          file_count=$(find data_archive -maxdepth 1 -name 'sackmann_data_*.csv' -print -quit | wc -l)
          if [ "$file_count" -eq 0 ]; then
            echo "Error: No CSV file found in data_archive after scraper run."
            exit 1 # Fail the workflow explicitly
          else
            echo "CSV file successfully created in data_archive."
            # Optional: list files found
            ls -l data_archive/sackmann_data_*.csv
          fi
      # *** END NEW STEP ***

      # --- Steps to Commit the generated CSV back to the repository ---
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage New CSV File(s)
        run: |
          if [ -d "data_archive" ]; then
            git add data_archive/*.csv
            echo "Staged CSV files from data_archive."
          else
            echo "data_archive directory not found, nothing to stage."
          fi

      - name: Commit New CSV(s) if any were staged
        run: |
          if ! git diff --staged --quiet; then
            git commit -m "Add/Update Sackmann data CSV(s) (`date -u +%Y-%m-%d`)"
            echo "Committed CSV changes."
          else
            echo "No changes to CSV files to commit."
          fi

      - name: Push CSV Changes
        run: |
           if [ $(git rev-list --count origin/${{ github.ref_name }}..${{ github.ref_name }}) -gt 0 ]; then
             git push origin ${{ github.ref_name }}
             echo "Pushed CSV commits to origin."
           else
             echo "No new commits to push."
           fi

      # --- End of CSV Commit Steps ---

      - name: Generate HTML Page from Latest CSV
        run: python generate_page.py # This now runs only if CSV exists

      # ... (Verify HTML, Setup Pages, Upload, Deploy steps remain the same) ...
      - name: Verify HTML Output
        run: |
          if [ ! -f index.html ]; then
            echo "Error: index.html not found after generation step."
            exit 1
          fi
          if ! grep -q "Last updated:" index.html; then
            echo "Warning: index.html does not seem to contain the 'Last updated' timestamp."
          fi
          if grep -q "" index.html; then
            echo "Warning: index.html might still contain the table placeholder."
          fi
          echo "HTML verification check complete."

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

